[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api/ppx/chat"
  to = "/.netlify/functions/ppx-chat"
  status = 200
  force = true

[[redirects]]
  from = "/api/ppx/media"
  to = "/.netlify/functions/ppx-media"
  status = 200
  force = true

[[redirects]]
  # Mirror Vite dev proxy: /geo/:cc/:level -> pinned GeoBoundaries file
  from = "/geo/:cc/:level"
  to = "https://raw.githubusercontent.com/wmgeolab/geoBoundaries/9469f09/releaseData/gbOpen/:cc/:level/geoBoundaries-:cc-:level.geojson"
  status = 200
  force = true


